### ISSUE TITLE
PHP Fatal error:  Class 'Fun\Lexing\UnknownTokenException' not found

### ISSUE THREAD

**Issue by raderio** [marco-fiset/marco-fiset.github.io#3]
http://marcofiset.com/programming-language-implementation-part-1-lexer/

**Comment by marco-fiset** [comment]
A fatal error usually indicates in which file, and at which line it occurred. I guess you can figure this out. Unfortunately, my code is long past this part, and I only started to introduce tags at the end of part 2. Every article after this one is tied with a tag in the Github repository, so you can see where you went wrong.

Since this is a class that was not found, you're probably missing a `use` statement at the top of the file, or the class is declared in the wrong namespace. It should be pretty easy to figure out.

**Comment by marco-fiset** [comment]
Without further information on your part, I'm afraid I'll have to close the issue now.
